@final
export class Operand {
    target: OpTarget;
    immediate: boolean;
    byteSize: u8;
    increment: boolean = false;
    decrement: boolean = false;
    signed: boolean = false;
    value: u8 = 0;
    constructor(name: OpTarget, immediate: boolean, byteSize: u8 = 0, constant: u8 = 0) {
        this.target = name;
        this.immediate = immediate;
        this.byteSize = byteSize;
        this.value = constant;
    }

    @inline
    static Value(immediate: boolean, byteSize: u8): Operand {
        return new Operand(OpTarget.Value, immediate, byteSize);
    }

    @inline
    static SignedValue(immediate: boolean, byteSize: u8): Operand {
        const op = new Operand(OpTarget.Value, immediate, byteSize);
        op.signed = true;
        return op;
    }

    @inline
    static Increment(name: OpTarget, byteSize: u8 = 0): Operand {
        const res = new Operand(name, false, byteSize);
        res.increment = true;
        return res;
    }

    @inline
    static Decrement(name: OpTarget, byteSize: u8 = 0): Operand {
        const res = new Operand(name, false, byteSize);
        res.decrement = true;
        return res;
    }

    @inline
    static Constant(value: u8): Operand {
        return new Operand(OpTarget.Constant, true, 0, value);
    }

    @inline
    static Condition(cond: OpCondition): Operand {
        return new Operand(OpTarget.Condition, true, 0, <u8>cond);
    }
}

export enum Op {
    ADC, ADD, AND, BIT, CALL, CCF, CP, CPL, DAA, DEC, DI, EI, HALT, ILLEGAL,
    INC, JP, JR, LD, LDH, NOP, OR, POP, PREFIX, PUSH, RES, RET, RETI, RL,
    RLA, RLC, RLCA, RR, RRA, RRC, RRCA, RST, SBC, SCF, SET, SLA, SRA, SRL,
    STOP, SUB, SWAP, XOR
}

export enum OpCondition {
    NonZero = 0, Zero = 1, NonCarry = 2, Carry = 3
}

export enum OpTarget {
    A, AF, B, C, BC, D, DE, E, H, HL, L, SP, Condition, Value, Constant
}

@final
export class Instruction {
    mnemonic: Op;
    byteSize: u8;
    cycleCounts: StaticArray<u8>;
    immediate: boolean;
    operands: StaticArray<Operand>
    constructor(mnemonic: Op, byteSize: u8, cycleCount: u8, immediate: boolean, operands: Array<Operand>) {
        this.mnemonic = mnemonic;
        this.byteSize = byteSize;
        this.cycleCounts = StaticArray.fromArray([cycleCount]);
        this.immediate = immediate;
        this.operands = StaticArray.fromArray(operands);
    }

    @inline
    static WithoutOperands(mnemonic: Op, byteSize: u8, cycleCount: u8): Instruction {
        return new Instruction(mnemonic, byteSize, cycleCount, false, new Array<Operand>(0));
    }

    @inline
    static Conditional(mnemonic: Op, byteSize: u8, cycleCount: u8, shortCycleCount: u8, operands: Array<Operand>): Instruction {
        const inst = new Instruction(mnemonic, byteSize, cycleCount, false, operands);
        inst.cycleCounts = StaticArray.fromArray([cycleCount, shortCycleCount]);
        return inst;
    }
}

export function getTotalInstructionSize(opCode: u8): u8 {
    let instr: Instruction = unprefixedOpCodes[opCode];
    return opCode == 0xCB ? (instr.byteSize + 1) : instr.byteSize;
}

export let unprefixedOpCodes: StaticArray<Instruction> = StaticArray.fromArray([
    /* 0x00 */ Instruction.WithoutOperands(Op.NOP, 1, 4),
    /* 0x01 */ new Instruction(Op.LD, 3, 12, true, [new Operand(OpTarget.BC, true), Operand.Value(true, 2)]),
    /* 0x02 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.BC, false), new Operand(OpTarget.A, true)]),
    /* 0x03 */ new Instruction(Op.INC, 1, 8, true, [new Operand(OpTarget.BC, true)]),
    /* 0x04 */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.B, true)]),
    /* 0x05 */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.B, true)]),
    /* 0x06 */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.B, true), Operand.Value(true, 1)]),
    /* 0x07 */ Instruction.WithoutOperands(Op.RLCA, 1, 4),
    /* 0x08 */ new Instruction(Op.LD, 3, 20, true, [Operand.Value(false, 2), new Operand(OpTarget.SP, true)]),
    /* 0x09 */ new Instruction(Op.ADD, 1, 8, true, [new Operand(OpTarget.HL, true), new Operand(OpTarget.BC, true)]),
    /* 0x0A */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.BC, false)]),
    /* 0x0B */ new Instruction(Op.DEC, 1, 8, true, [new Operand(OpTarget.BC, true)]),
    /* 0x0C */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.C, true)]),
    /* 0x0D */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.C, true)]),
    /* 0x0E */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.C, true), Operand.Value(true, 1)]),
    /* 0x0F */ Instruction.WithoutOperands(Op.RRCA, 1, 4),
    /* 0x10 */ new Instruction(Op.STOP, 2, 4, true, [Operand.Value(true, 1)]),
    /* 0x11 */ new Instruction(Op.LD, 3, 12, true, [new Operand(OpTarget.DE, true), Operand.Value(true, 2)]),
    /* 0x12 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.DE, false), new Operand(OpTarget.A, true)]),
    /* 0x13 */ new Instruction(Op.INC, 1, 8, true, [new Operand(OpTarget.DE, true)]),
    /* 0x14 */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.D, true)]),
    /* 0x15 */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.D, true)]),
    /* 0x16 */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.D, true), Operand.Value(true, 1)]),
    /* 0x17 */ Instruction.WithoutOperands(Op.RLA, 1, 4),
    /* 0x18 */ new Instruction(Op.JR, 2, 12, true, [Operand.SignedValue(true, 1)]),
    /* 0x19 */ new Instruction(Op.ADD, 1, 8, true, [new Operand(OpTarget.HL, true), new Operand(OpTarget.DE, true)]),
    /* 0x1A */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.DE, false)]),
    /* 0x1B */ new Instruction(Op.DEC, 1, 8, true, [new Operand(OpTarget.DE, true)]),
    /* 0x1C */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.E, true)]),
    /* 0x1D */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.E, true)]),
    /* 0x1E */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.E, true), Operand.Value(true, 1)]),
    /* 0x1F */ Instruction.WithoutOperands(Op.RRA, 1, 4),
    /* 0x20 */ Instruction.Conditional(Op.JR, 2, 12, 8, [Operand.Condition(OpCondition.NonZero), Operand.SignedValue(true, 1)]),
    /* 0x21 */ new Instruction(Op.LD, 3, 12, true, [new Operand(OpTarget.HL, true), Operand.Value(true, 2)]),
    /* 0x22 */ new Instruction(Op.LD, 1, 8, true, [Operand.Increment(OpTarget.HL), new Operand(OpTarget.A, true)]),
    /* 0x23 */ new Instruction(Op.INC, 1, 8, true, [new Operand(OpTarget.HL, true)]),
    /* 0x24 */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.H, true)]),
    /* 0x25 */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.H, true)]),
    /* 0x26 */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.H, true), Operand.Value(true, 1)]),
    /* 0x27 */ Instruction.WithoutOperands(Op.DAA, 1, 4),
    /* 0x28 */ Instruction.Conditional(Op.JR, 2, 12, 8, [Operand.Condition(OpCondition.Zero), Operand.SignedValue(true, 1)]),
    /* 0x29 */ new Instruction(Op.ADD, 1, 8, true, [new Operand(OpTarget.HL, true), new Operand(OpTarget.HL, true)]),
    /* 0x2A */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.A, true), Operand.Increment(OpTarget.HL)]),
    /* 0x2B */ new Instruction(Op.DEC, 1, 8, true, [new Operand(OpTarget.HL, true)]),
    /* 0x2C */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.L, true)]),
    /* 0x2D */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.L, true)]),
    /* 0x2E */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.L, true), Operand.Value(true, 1)]),
    /* 0x2F */ Instruction.WithoutOperands(Op.CPL, 1, 4),
    /* 0x30 */ Instruction.Conditional(Op.JR, 2, 12, 8, [Operand.Condition(OpCondition.NonCarry), Operand.SignedValue(true, 1)]),
    /* 0x31 */ new Instruction(Op.LD, 3, 12, true, [new Operand(OpTarget.SP, true), Operand.Value(true, 2)]),
    /* 0x32 */ new Instruction(Op.LD, 1, 8, true, [Operand.Decrement(OpTarget.HL), new Operand(OpTarget.A, true)]),
    /* 0x33 */ new Instruction(Op.INC, 1, 8, true, [new Operand(OpTarget.SP, true)]),
    /* 0x34 */ new Instruction(Op.INC, 1, 12, true, [new Operand(OpTarget.HL, false)]),
    /* 0x35 */ new Instruction(Op.DEC, 1, 12, true, [new Operand(OpTarget.HL, false)]),
    /* 0x36 */ new Instruction(Op.LD, 2, 12, true, [new Operand(OpTarget.HL, false), Operand.Value(true, 1)]),
    /* 0x37 */ Instruction.WithoutOperands(Op.SCF, 1, 4),
    /* 0x38 */ Instruction.Conditional(Op.JR, 2, 12, 8, [Operand.Condition(OpCondition.Carry), Operand.SignedValue(true, 1)]),
    /* 0x39 */ new Instruction(Op.ADD, 1, 8, true, [new Operand(OpTarget.HL, true), new Operand(OpTarget.SP, true)]),
    /* 0x3A */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.A, true), Operand.Decrement(OpTarget.HL)]),
    /* 0x3B */ new Instruction(Op.DEC, 1, 8, true, [new Operand(OpTarget.SP, true)]),
    /* 0x3C */ new Instruction(Op.INC, 1, 4, true, [new Operand(OpTarget.A, true)]),
    /* 0x3D */ new Instruction(Op.DEC, 1, 4, true, [new Operand(OpTarget.A, true)]),
    /* 0x3E */ new Instruction(Op.LD, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0x3F */ Instruction.WithoutOperands(Op.CCF, 1, 4),
    /* 0x40 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.B, true)]),
    /* 0x41 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.C, true)]),
    /* 0x42 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.D, true)]),
    /* 0x43 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.E, true)]),
    /* 0x44 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.H, true)]),
    /* 0x45 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.L, true)]),
    /* 0x46 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.HL, false)]),
    /* 0x47 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.B, true), new Operand(OpTarget.A, true)]),
    /* 0x48 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.B, true)]),
    /* 0x49 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.C, true)]),
    /* 0x4A */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.D, true)]),
    /* 0x4B */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.E, true)]),
    /* 0x4C */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.H, true)]),
    /* 0x4D */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.L, true)]),
    /* 0x4E */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.HL, false)]),
    /* 0x4F */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.C, true), new Operand(OpTarget.A, true)]),
    /* 0x50 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.B, true)]),
    /* 0x51 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.C, true)]),
    /* 0x52 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.D, true)]),
    /* 0x53 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.E, true)]),
    /* 0x54 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.H, true)]),
    /* 0x55 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.L, true)]),
    /* 0x56 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.HL, false)]),
    /* 0x57 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.D, true), new Operand(OpTarget.A, true)]),
    /* 0x58 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.B, true)]),
    /* 0x59 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.C, true)]),
    /* 0x5A */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.D, true)]),
    /* 0x5B */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.E, true)]),
    /* 0x5C */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.H, true)]),
    /* 0x5D */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.L, true)]),
    /* 0x5E */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.HL, false)]),
    /* 0x5F */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.E, true), new Operand(OpTarget.A, true)]),
    /* 0x60 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.B, true)]),
    /* 0x61 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.C, true)]),
    /* 0x62 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.D, true)]),
    /* 0x63 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.E, true)]),
    /* 0x64 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.H, true)]),
    /* 0x65 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.L, true)]),
    /* 0x66 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.HL, false)]),
    /* 0x67 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.H, true), new Operand(OpTarget.A, true)]),
    /* 0x68 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.B, true)]),
    /* 0x69 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.C, true)]),
    /* 0x6A */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.D, true)]),
    /* 0x6B */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.E, true)]),
    /* 0x6C */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.H, true)]),
    /* 0x6D */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.L, true)]),
    /* 0x6E */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.HL, false)]),
    /* 0x6F */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.L, true), new Operand(OpTarget.A, true)]),
    /* 0x70 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.B, true)]),
    /* 0x71 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.C, true)]),
    /* 0x72 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.D, true)]),
    /* 0x73 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.E, true)]),
    /* 0x74 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.H, true)]),
    /* 0x75 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.L, true)]),
    /* 0x76 */ Instruction.WithoutOperands(Op.HALT, 1, 4),
    /* 0x77 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.HL, false), new Operand(OpTarget.A, true)]),
    /* 0x78 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0x79 */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0x7A */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0x7B */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0x7C */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0x7D */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0x7E */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0x7F */ new Instruction(Op.LD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0x80 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0x81 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0x82 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0x83 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0x84 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0x85 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0x86 */ new Instruction(Op.ADD, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0x87 */ new Instruction(Op.ADD, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0x88 */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0x89 */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0x8A */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0x8B */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0x8C */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0x8D */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0x8E */ new Instruction(Op.ADC, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0x8F */ new Instruction(Op.ADC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0x90 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0x91 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0x92 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0x93 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0x94 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0x95 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0x96 */ new Instruction(Op.SUB, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0x97 */ new Instruction(Op.SUB, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0x98 */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0x99 */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0x9A */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0x9B */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0x9C */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0x9D */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0x9E */ new Instruction(Op.SBC, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0x9F */ new Instruction(Op.SBC, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0xA0 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0xA1 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0xA2 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0xA3 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0xA4 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0xA5 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0xA6 */ new Instruction(Op.AND, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0xA7 */ new Instruction(Op.AND, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0xA8 */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0xA9 */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0xAA */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0xAB */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0xAC */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0xAD */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0xAE */ new Instruction(Op.XOR, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0xAF */ new Instruction(Op.XOR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0xB0 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0xB1 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0xB2 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0xB3 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0xB4 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0xB5 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0xB6 */ new Instruction(Op.OR, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0xB7 */ new Instruction(Op.OR, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0xB8 */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.B, true)]),
    /* 0xB9 */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, true)]),
    /* 0xBA */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.D, true)]),
    /* 0xBB */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.E, true)]),
    /* 0xBC */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.H, true)]),
    /* 0xBD */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.L, true)]),
    /* 0xBE */ new Instruction(Op.CP, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.HL, false)]),
    /* 0xBF */ new Instruction(Op.CP, 1, 4, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.A, true)]),
    /* 0xC0 */ Instruction.Conditional(Op.RET, 1, 20, 8, [Operand.Condition(OpCondition.NonZero)]),
    /* 0xC1 */ new Instruction(Op.POP, 1, 12, true, [new Operand(OpTarget.BC, true)]),
    /* 0xC2 */ Instruction.Conditional(Op.JP, 3, 16, 12, [Operand.Condition(OpCondition.NonZero), Operand.Value(true, 2)]),
    /* 0xC3 */ new Instruction(Op.JP, 3, 16, true, [Operand.Value(true, 2)]),
    /* 0xC4 */ Instruction.Conditional(Op.CALL, 3, 24, 12, [Operand.Condition(OpCondition.NonZero), Operand.Value(true, 2)]),
    /* 0xC5 */ new Instruction(Op.PUSH, 1, 16, true, [new Operand(OpTarget.BC, true)]),
    /* 0xC6 */ new Instruction(Op.ADD, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xC7 */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0)]),
    /* 0xC8 */ Instruction.Conditional(Op.RET, 1, 20, 8, [Operand.Condition(OpCondition.Zero)]),
    /* 0xC9 */ Instruction.WithoutOperands(Op.RET, 1, 16),
    /* 0xCA */ Instruction.Conditional(Op.JP, 3, 16, 12, [Operand.Condition(OpCondition.Zero), Operand.Value(true, 2)]),
    /* 0xCB */ Instruction.WithoutOperands(Op.PREFIX, 1, 4),
    /* 0xCC */ Instruction.Conditional(Op.CALL, 3, 24, 12, [Operand.Condition(OpCondition.Zero), Operand.Value(true, 2)]),
    /* 0xCD */ new Instruction(Op.CALL, 3, 24, true, [Operand.Value(true, 2)]),
    /* 0xCE */ new Instruction(Op.ADC, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xCF */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x8)]),
    /* 0xD0 */ Instruction.Conditional(Op.RET, 1, 20, 8, [Operand.Condition(OpCondition.NonCarry)]),
    /* 0xD1 */ new Instruction(Op.POP, 1, 12, true, [new Operand(OpTarget.DE, true)]),
    /* 0xD2 */ Instruction.Conditional(Op.JP, 3, 16, 12, [Operand.Condition(OpCondition.NonCarry), Operand.Value(true, 2)]),
    /* 0xD3 */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xD4 */ Instruction.Conditional(Op.CALL, 3, 24, 12, [Operand.Condition(OpCondition.NonCarry), Operand.Value(true, 2)]),
    /* 0xD5 */ new Instruction(Op.PUSH, 1, 16, true, [new Operand(OpTarget.DE, true)]),
    /* 0xD6 */ new Instruction(Op.SUB, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xD7 */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x10)]),
    /* 0xD8 */ Instruction.Conditional(Op.RET, 1, 20, 8, [Operand.Condition(OpCondition.Carry)]),
    /* 0xD9 */ Instruction.WithoutOperands(Op.RETI, 1, 16),
    /* 0xDA */ Instruction.Conditional(Op.JP, 3, 16, 12, [Operand.Condition(OpCondition.Carry), Operand.Value(true, 2)]),
    /* 0xDB */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xDC */ Instruction.Conditional(Op.CALL, 3, 24, 12, [Operand.Condition(OpCondition.Carry), Operand.Value(true, 2)]),
    /* 0xDD */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xDE */ new Instruction(Op.SBC, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xDF */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x18)]),
    /* 0xE0 */ new Instruction(Op.LDH, 2, 12, true, [Operand.Value(false, 1), new Operand(OpTarget.A, true)]),
    /* 0xE1 */ new Instruction(Op.POP, 1, 12, true, [new Operand(OpTarget.HL, true)]),
    /* 0xE2 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.C, false), new Operand(OpTarget.A, true)]),
    /* 0xE3 */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xE4 */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xE5 */ new Instruction(Op.PUSH, 1, 16, true, [new Operand(OpTarget.HL, true)]),
    /* 0xE6 */ new Instruction(Op.AND, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xE7 */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x20)]),
    /* 0xE8 */ new Instruction(Op.ADD, 2, 16, true, [new Operand(OpTarget.SP, true), Operand.SignedValue(true, 1)]),
    /* 0xE9 */ new Instruction(Op.JP, 1, 4, true, [new Operand(OpTarget.HL, true)]),
    /* 0xEA */ new Instruction(Op.LD, 3, 16, true, [Operand.Value(false, 2), new Operand(OpTarget.A, true)]),
    /* 0xEB */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xEC */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xED */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xEE */ new Instruction(Op.XOR, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xEF */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x28)]),
    /* 0xF0 */ new Instruction(Op.LDH, 2, 12, true, [new Operand(OpTarget.A, true), Operand.Value(false, 1)]),
    /* 0xF1 */ new Instruction(Op.POP, 1, 12, true, [new Operand(OpTarget.AF, true)]),
    /* 0xF2 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.A, true), new Operand(OpTarget.C, false)]),
    /* 0xF3 */ Instruction.WithoutOperands(Op.DI, 1, 4),
    /* 0xF4 */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xF5 */ new Instruction(Op.PUSH, 1, 16, true, [new Operand(OpTarget.AF, true)]),
    /* 0xF6 */ new Instruction(Op.OR, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xF7 */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x30)]),
    /* 0xF8 */ new Instruction(Op.LD, 2, 12, true, [new Operand(OpTarget.HL, true), new Operand(OpTarget.SP, true), Operand.SignedValue(true, 1)]),
    /* 0xF9 */ new Instruction(Op.LD, 1, 8, true, [new Operand(OpTarget.SP, true), new Operand(OpTarget.HL, true)]),
    /* 0xFA */ new Instruction(Op.LD, 3, 16, true, [new Operand(OpTarget.A, true), Operand.Value(false, 2)]),
    /* 0xFB */ Instruction.WithoutOperands(Op.EI, 1, 4),
    /* 0xFC */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xFD */ Instruction.WithoutOperands(Op.ILLEGAL, 1, 4),
    /* 0xFE */ new Instruction(Op.CP, 2, 8, true, [new Operand(OpTarget.A, true), Operand.Value(true, 1)]),
    /* 0xFF */ new Instruction(Op.RST, 1, 16, true, [Operand.Constant(0x38)]),
]);

export let prefixedOpCodes: StaticArray<Instruction> = StaticArray.fromArray([
    /* 0x00 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x01 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x02 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x03 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x04 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x05 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x06 */ new Instruction(Op.RLC, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x07 */ new Instruction(Op.RLC, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x08 */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x09 */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x0A */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x0B */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x0C */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x0D */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x0E */ new Instruction(Op.RRC, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x0F */ new Instruction(Op.RRC, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x10 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x11 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x12 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x13 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x14 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x15 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x16 */ new Instruction(Op.RL, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x17 */ new Instruction(Op.RL, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x18 */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x19 */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x1A */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x1B */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x1C */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x1D */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x1E */ new Instruction(Op.RR, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x1F */ new Instruction(Op.RR, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x20 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x21 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x22 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x23 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x24 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x25 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x26 */ new Instruction(Op.SLA, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x27 */ new Instruction(Op.SLA, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x28 */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x29 */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x2A */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x2B */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x2C */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x2D */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x2E */ new Instruction(Op.SRA, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x2F */ new Instruction(Op.SRA, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x30 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x31 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x32 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x33 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x34 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x35 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x36 */ new Instruction(Op.SWAP, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x37 */ new Instruction(Op.SWAP, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x38 */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.B, true)]),
    /* 0x39 */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.C, true)]),
    /* 0x3A */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.D, true)]),
    /* 0x3B */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.E, true)]),
    /* 0x3C */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.H, true)]),
    /* 0x3D */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.L, true)]),
    /* 0x3E */ new Instruction(Op.SRL, 2, 16, false, [new Operand(OpTarget.HL, false)]),
    /* 0x3F */ new Instruction(Op.SRL, 2, 8, true, [new Operand(OpTarget.A, true)]),
    /* 0x40 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.B, true)]),
    /* 0x41 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.C, true)]),
    /* 0x42 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.D, true)]),
    /* 0x43 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.E, true)]),
    /* 0x44 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.H, true)]),
    /* 0x45 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.L, true)]),
    /* 0x46 */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(0), new Operand(OpTarget.HL, false)]),
    /* 0x47 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.A, true)]),
    /* 0x48 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.B, true)]),
    /* 0x49 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.C, true)]),
    /* 0x4A */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.D, true)]),
    /* 0x4B */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.E, true)]),
    /* 0x4C */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.H, true)]),
    /* 0x4D */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.L, true)]),
    /* 0x4E */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(1), new Operand(OpTarget.HL, false)]),
    /* 0x4F */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.A, true)]),
    /* 0x50 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.B, true)]),
    /* 0x51 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.C, true)]),
    /* 0x52 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.D, true)]),
    /* 0x53 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.E, true)]),
    /* 0x54 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.H, true)]),
    /* 0x55 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.L, true)]),
    /* 0x56 */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(2), new Operand(OpTarget.HL, false)]),
    /* 0x57 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.A, true)]),
    /* 0x58 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.B, true)]),
    /* 0x59 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.C, true)]),
    /* 0x5A */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.D, true)]),
    /* 0x5B */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.E, true)]),
    /* 0x5C */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.H, true)]),
    /* 0x5D */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.L, true)]),
    /* 0x5E */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(3), new Operand(OpTarget.HL, false)]),
    /* 0x5F */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.A, true)]),
    /* 0x60 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.B, true)]),
    /* 0x61 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.C, true)]),
    /* 0x62 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.D, true)]),
    /* 0x63 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.E, true)]),
    /* 0x64 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.H, true)]),
    /* 0x65 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.L, true)]),
    /* 0x66 */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(4), new Operand(OpTarget.HL, false)]),
    /* 0x67 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.A, true)]),
    /* 0x68 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.B, true)]),
    /* 0x69 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.C, true)]),
    /* 0x6A */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.D, true)]),
    /* 0x6B */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.E, true)]),
    /* 0x6C */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.H, true)]),
    /* 0x6D */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.L, true)]),
    /* 0x6E */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(5), new Operand(OpTarget.HL, false)]),
    /* 0x6F */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.A, true)]),
    /* 0x70 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.B, true)]),
    /* 0x71 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.C, true)]),
    /* 0x72 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.D, true)]),
    /* 0x73 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.E, true)]),
    /* 0x74 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.H, true)]),
    /* 0x75 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.L, true)]),
    /* 0x76 */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(6), new Operand(OpTarget.HL, false)]),
    /* 0x77 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.A, true)]),
    /* 0x78 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.B, true)]),
    /* 0x79 */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.C, true)]),
    /* 0x7A */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.D, true)]),
    /* 0x7B */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.E, true)]),
    /* 0x7C */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.H, true)]),
    /* 0x7D */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.L, true)]),
    /* 0x7E */ new Instruction(Op.BIT, 2, 12, false, [Operand.Constant(7), new Operand(OpTarget.HL, false)]),
    /* 0x7F */ new Instruction(Op.BIT, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.A, true)]),
    /* 0x80 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.B, true)]),
    /* 0x81 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.C, true)]),
    /* 0x82 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.D, true)]),
    /* 0x83 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.E, true)]),
    /* 0x84 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.H, true)]),
    /* 0x85 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.L, true)]),
    /* 0x86 */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(0), new Operand(OpTarget.HL, false)]),
    /* 0x87 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.A, true)]),
    /* 0x88 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.B, true)]),
    /* 0x89 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.C, true)]),
    /* 0x8A */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.D, true)]),
    /* 0x8B */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.E, true)]),
    /* 0x8C */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.H, true)]),
    /* 0x8D */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.L, true)]),
    /* 0x8E */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(1), new Operand(OpTarget.HL, false)]),
    /* 0x8F */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.A, true)]),
    /* 0x90 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.B, true)]),
    /* 0x91 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.C, true)]),
    /* 0x92 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.D, true)]),
    /* 0x93 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.E, true)]),
    /* 0x94 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.H, true)]),
    /* 0x95 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.L, true)]),
    /* 0x96 */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(2), new Operand(OpTarget.HL, false)]),
    /* 0x97 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.A, true)]),
    /* 0x98 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.B, true)]),
    /* 0x99 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.C, true)]),
    /* 0x9A */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.D, true)]),
    /* 0x9B */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.E, true)]),
    /* 0x9C */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.H, true)]),
    /* 0x9D */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.L, true)]),
    /* 0x9E */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(3), new Operand(OpTarget.HL, false)]),
    /* 0x9F */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.A, true)]),
    /* 0xA0 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.B, true)]),
    /* 0xA1 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.C, true)]),
    /* 0xA2 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.D, true)]),
    /* 0xA3 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.E, true)]),
    /* 0xA4 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.H, true)]),
    /* 0xA5 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.L, true)]),
    /* 0xA6 */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(4), new Operand(OpTarget.HL, false)]),
    /* 0xA7 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.A, true)]),
    /* 0xA8 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.B, true)]),
    /* 0xA9 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.C, true)]),
    /* 0xAA */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.D, true)]),
    /* 0xAB */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.E, true)]),
    /* 0xAC */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.H, true)]),
    /* 0xAD */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.L, true)]),
    /* 0xAE */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(5), new Operand(OpTarget.HL, false)]),
    /* 0xAF */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.A, true)]),
    /* 0xB0 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.B, true)]),
    /* 0xB1 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.C, true)]),
    /* 0xB2 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.D, true)]),
    /* 0xB3 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.E, true)]),
    /* 0xB4 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.H, true)]),
    /* 0xB5 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.L, true)]),
    /* 0xB6 */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(6), new Operand(OpTarget.HL, false)]),
    /* 0xB7 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.A, true)]),
    /* 0xB8 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.B, true)]),
    /* 0xB9 */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.C, true)]),
    /* 0xBA */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.D, true)]),
    /* 0xBB */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.E, true)]),
    /* 0xBC */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.H, true)]),
    /* 0xBD */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.L, true)]),
    /* 0xBE */ new Instruction(Op.RES, 2, 16, false, [Operand.Constant(7), new Operand(OpTarget.HL, false)]),
    /* 0xBF */ new Instruction(Op.RES, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.A, true)]),
    /* 0xC0 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.B, true)]),
    /* 0xC1 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.C, true)]),
    /* 0xC2 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.D, true)]),
    /* 0xC3 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.E, true)]),
    /* 0xC4 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.H, true)]),
    /* 0xC5 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.L, true)]),
    /* 0xC6 */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(0), new Operand(OpTarget.HL, false)]),
    /* 0xC7 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(0), new Operand(OpTarget.A, true)]),
    /* 0xC8 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.B, true)]),
    /* 0xC9 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.C, true)]),
    /* 0xCA */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.D, true)]),
    /* 0xCB */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.E, true)]),
    /* 0xCC */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.H, true)]),
    /* 0xCD */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.L, true)]),
    /* 0xCE */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(1), new Operand(OpTarget.HL, false)]),
    /* 0xCF */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(1), new Operand(OpTarget.A, true)]),
    /* 0xD0 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.B, true)]),
    /* 0xD1 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.C, true)]),
    /* 0xD2 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.D, true)]),
    /* 0xD3 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.E, true)]),
    /* 0xD4 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.H, true)]),
    /* 0xD5 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.L, true)]),
    /* 0xD6 */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(2), new Operand(OpTarget.HL, false)]),
    /* 0xD7 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(2), new Operand(OpTarget.A, true)]),
    /* 0xD8 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.B, true)]),
    /* 0xD9 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.C, true)]),
    /* 0xDA */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.D, true)]),
    /* 0xDB */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.E, true)]),
    /* 0xDC */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.H, true)]),
    /* 0xDD */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.L, true)]),
    /* 0xDE */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(3), new Operand(OpTarget.HL, false)]),
    /* 0xDF */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(3), new Operand(OpTarget.A, true)]),
    /* 0xE0 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.B, true)]),
    /* 0xE1 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.C, true)]),
    /* 0xE2 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.D, true)]),
    /* 0xE3 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.E, true)]),
    /* 0xE4 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.H, true)]),
    /* 0xE5 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.L, true)]),
    /* 0xE6 */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(4), new Operand(OpTarget.HL, false)]),
    /* 0xE7 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(4), new Operand(OpTarget.A, true)]),
    /* 0xE8 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.B, true)]),
    /* 0xE9 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.C, true)]),
    /* 0xEA */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.D, true)]),
    /* 0xEB */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.E, true)]),
    /* 0xEC */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.H, true)]),
    /* 0xED */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.L, true)]),
    /* 0xEE */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(5), new Operand(OpTarget.HL, false)]),
    /* 0xEF */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(5), new Operand(OpTarget.A, true)]),
    /* 0xF0 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.B, true)]),
    /* 0xF1 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.C, true)]),
    /* 0xF2 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.D, true)]),
    /* 0xF3 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.E, true)]),
    /* 0xF4 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.H, true)]),
    /* 0xF5 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.L, true)]),
    /* 0xF6 */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(6), new Operand(OpTarget.HL, false)]),
    /* 0xF7 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(6), new Operand(OpTarget.A, true)]),
    /* 0xF8 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.B, true)]),
    /* 0xF9 */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.C, true)]),
    /* 0xFA */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.D, true)]),
    /* 0xFB */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.E, true)]),
    /* 0xFC */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.H, true)]),
    /* 0xFD */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.L, true)]),
    /* 0xFE */ new Instruction(Op.SET, 2, 16, false, [Operand.Constant(7), new Operand(OpTarget.HL, false)]),
    /* 0xFF */ new Instruction(Op.SET, 2, 8, false, [Operand.Constant(7), new Operand(OpTarget.A, true)])
]);