import { IntType } from "../cpu/interrupts";
import { Op, OpCondition, OpTarget } from "../cpu/opcodes";
import { CGBMode } from "../metadata";
import { uToHex } from "../utils/stringUtils";

export const conditionNames: Map<OpCondition, string> = new Map<OpCondition, string>();
conditionNames.set(OpCondition.NonZero, "NZ");
conditionNames.set(OpCondition.Zero, "Z");
conditionNames.set(OpCondition.NonCarry, "NC");
conditionNames.set(OpCondition.Carry, "C");

export function getCartridgeTypeName(type: u8): string {
    if (!CartridgeTypeNames.has(type))
        return 'Unknown: ' + uToHex<u8>(type);
    return CartridgeTypeNames.get(type);
}

export const CartridgeTypeNames: Map<u8, string> = new Map<u8, string>();
CartridgeTypeNames.set(0x00, 'ROM_ONLY');
CartridgeTypeNames.set(0x01, 'MBC1');
CartridgeTypeNames.set(0x02, 'MBC1_RAM');
CartridgeTypeNames.set(0x03, 'MBC1_RAM_BATTERY');
CartridgeTypeNames.set(0x05, 'MBC2');
CartridgeTypeNames.set(0x06, 'MBC2_BATTERY');
CartridgeTypeNames.set(0x08, 'ROM_RAM_1');
CartridgeTypeNames.set(0x09, 'ROM_RAM_BATTERY_1');
CartridgeTypeNames.set(0x0B, 'MMM01');
CartridgeTypeNames.set(0x0C, 'MMM01_RAM');
CartridgeTypeNames.set(0x0D, 'MMM01_RAM_BATTERY');
CartridgeTypeNames.set(0x0F, 'MBC3_TIMER_BATTERY');
CartridgeTypeNames.set(0x10, 'MBC3_TIMER_RAM_BATTERY_2');
CartridgeTypeNames.set(0x11, 'MBC3');
CartridgeTypeNames.set(0x12, 'MBC3_RAM_2');
CartridgeTypeNames.set(0x13, 'MBC3_RAM_BATTERY_2');
CartridgeTypeNames.set(0x19, 'MBC5');
CartridgeTypeNames.set(0x1A, 'MBC5_RAM');
CartridgeTypeNames.set(0x1B, 'MBC5_RAM_BATTERY');
CartridgeTypeNames.set(0x1C, 'MBC5_RUMBLE');
CartridgeTypeNames.set(0x1D, 'MBC5_RUMBLE_RAM');
CartridgeTypeNames.set(0x1E, 'MBC5_RUMBLE_RAM_BATTERY');
CartridgeTypeNames.set(0x20, 'MBC6');
CartridgeTypeNames.set(0x22, 'MBC7_SENSOR_RUMBLE_RAM_BATTERY');
CartridgeTypeNames.set(0xFC, 'POCKET_CAMERA');
CartridgeTypeNames.set(0xFD, 'BANDAI_TAMA5');
CartridgeTypeNames.set(0xFE, 'HuC3');
CartridgeTypeNames.set(0xFF, 'HuC1_RAM_BATTERY');

export const CGBModeNames = new Map<CGBMode, string>();
CGBModeNames.set(CGBMode.NonCGB, "NonCGB");
CGBModeNames.set(CGBMode.PartialCGB, "PartialCGB");
CGBModeNames.set(CGBMode.CGBOnly, "CGBOnly");

export const opNames: Map<Op, string> = new Map<Op, string>();
opNames.set(Op.ADC, "ADC");
opNames.set(Op.ADD, "ADD");
opNames.set(Op.AND, "AND");
opNames.set(Op.BIT, "BIT");
opNames.set(Op.CALL, "CALL");
opNames.set(Op.CCF, "CCF");
opNames.set(Op.CP, "CP");
opNames.set(Op.CPL, "CPL");
opNames.set(Op.DAA, "DAA");
opNames.set(Op.DEC, "DEC");
opNames.set(Op.DI, "DI");
opNames.set(Op.EI, "EI");
opNames.set(Op.HALT, "HALT");
opNames.set(Op.ILLEGAL, "ILLEGAL");
opNames.set(Op.INC, "INC");
opNames.set(Op.JP, "JP");
opNames.set(Op.JR, "JR");
opNames.set(Op.LD, "LD");
opNames.set(Op.LDH, "LDH");
opNames.set(Op.NOP, "NOP");
opNames.set(Op.OR, "OR");
opNames.set(Op.POP, "POP");
opNames.set(Op.PREFIX, "PREFIX");
opNames.set(Op.PUSH, "PUSH");
opNames.set(Op.RES, "RES");
opNames.set(Op.RET, "RET");
opNames.set(Op.RETI, "RETI");
opNames.set(Op.RL, "RL");
opNames.set(Op.RLA, "RLA");
opNames.set(Op.RLC, "RLC");
opNames.set(Op.RLCA, "RLCA");
opNames.set(Op.RR, "RR");
opNames.set(Op.RRA, "RRA");
opNames.set(Op.RRC, "RRC");
opNames.set(Op.RRCA, "RRCA");
opNames.set(Op.RST, "RST");
opNames.set(Op.SBC, "SBC");
opNames.set(Op.SCF, "SCF");
opNames.set(Op.SET, "SET");
opNames.set(Op.SLA, "SLA");
opNames.set(Op.SRA, "SRA");
opNames.set(Op.SRL, "SRL");
opNames.set(Op.STOP, "STOP");
opNames.set(Op.SUB, "SUB");
opNames.set(Op.SWAP, "SWAP");
opNames.set(Op.XOR, "XOR");

export const targetNames: Map<OpTarget, string> = new Map<OpTarget, string>();
targetNames.set(OpTarget.A, "A");
targetNames.set(OpTarget.AF, "AF");
targetNames.set(OpTarget.B, "B");
targetNames.set(OpTarget.BC, "BC");
targetNames.set(OpTarget.C, "C");
targetNames.set(OpTarget.D, "D");
targetNames.set(OpTarget.DE, "DE");
targetNames.set(OpTarget.E, "E");
targetNames.set(OpTarget.H, "H");
targetNames.set(OpTarget.HL, "HL");
targetNames.set(OpTarget.L, "L");
targetNames.set(OpTarget.SP, "SP");
targetNames.set(OpTarget.Value, "Value");
targetNames.set(OpTarget.Constant, "Constant");


export const IntNames: Map<IntType, string> = new Map<IntType, string>();
IntNames.set(IntType.VBlank, "VBlank");
IntNames.set(IntType.LcdSTAT, "LcdSTAT");
IntNames.set(IntType.Timer, "Timer");
IntNames.set(IntType.Serial, "Serial");
IntNames.set(IntType.Joypad, "Joypad");
